### PR TITLE
Fix people tab

### PR DESCRIPTION
**Pull request by clpetix**
Updated the people tab: 

1. Sort alphabetically by last name. 
2. Updated Levi's role to candidate and description to match the research tab. 
3. Updated Mohammadreza's role to candidate.

### CODE REVIEW

**Comment by mphoward** [comment]
Thank you! Do we have an alumni section ready to use? If we do, Matthew can be moved there in this PR since he was a summer student.

**Comment by clpetix** [comment]
> Thank you! Do we have an alumni section ready to use? If we do, Matthew can be moved there in this PR since he was a summer student.

@pgkovakas could you check this out since you set up that system?

**Comment by clpetix** [comment]
@mphoward this should be ready for your review!

**Review by mphoward — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
